name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3.0.0
      with:
        java-version: 17
        distribution: 'adopt'
        java-package: jdk
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.1.3
      with:
        arguments: bootJar
    - name: docker build
      run: |
        docker build . --file Dockerfile --tag timbo925/musica:latest --tag timbo925/musica:version_$GITHUB_RUN_NUMBER
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD    
    - name: docker push
      run: |
        docker push timbo925/musica --all-tags
    - uses: fateyan/action-discord-notifier@v1
      with:
        message-title: Successfullly pushed to docker
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
