name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3.0.0
      with:
        java-version: 17
        distribution: 'adopt'
        java-package: jdk
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.1.3
      with:
        arguments: test
